name: Keepalive Python

on:
  workflow_dispatch:
  schedule:
   - cron: '* 0,6,8,9,10 * * *'
   

    
    

jobs:
  keepalive:
    runs-on: ubuntu-latest
    timeout-minutes: 350  # GitHub Actions 单 job 最长 6 小时，别设太接近 360

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps (if any)
        run: |
          pip install -U pip
          # pip install -r requirements.txt  # 如果有依赖就打开

      - name: Run keepalive script
        run: |
          python keepalive.py
